services:
  - type: web
    name: gymmate
    env: php
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gymmate.onrender.com
